### ISSUE TITLE
`cmake buildclang/nosan error`

### ISSUE THREAD

**Issue by krishvishal** [LoopModels/Math#13]
I've run the following commands

```bash
CXXFLAGS="" CXX=clang++ cmake -S test -B buildclang/nosan/ -DCMAKE_BUILD_TYPE=Debug #worked fine
cmake --build buildclang/nosan/ # error
```

clang version: 16

Stacktrace:

```bash
[  0%] Built target Math
[  4%] Clearing out old coverage data.
[  4%] Built target clean_coverage
[  8%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/src/gtest-all.cc:38:
In file included from /home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/gtest.h:65:
In file included from /home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/gtest-death-test.h:43:
In file included from /home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/internal/gtest-death-test-internal.h:47:
In file included from /home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/gtest-matchers.h:48:
/home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/gtest-printers.h:532:9: warning: implicit conversion from 'int32_t' (aka 'int') to 'float' may lose precision [-Wimplicit-int-float-conversion]
    if (static_cast<int32_t>(val * mulfor6 + 0.5) / mulfor6 == val) return 6;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
/home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/gtest-printers.h:551:17: note: in instantiation of function template specialization 'testing::internal::AppropriateResolution<float>' requested here
  os->precision(AppropriateResolution(f));
                ^
/home/kv/work/comp/loopmodels/Math/buildclang/nosan/_deps/googletest-src/googletest/include/gtest/gtest-printers.h:544:9: warning: implicit conversion from 'int32_t' (aka 'int') to 'float' may lose precision [-Wimplicit-int-float-conversion]
    if (static_cast<int32_t>(val / divfor6 + 0.5) * divfor6 == val) return 6;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
2 warnings generated.
[ 13%] Linking CXX static library ../../../lib/libgtest.a
[ 13%] Built target gtest
[ 17%] Building CXX object _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 21%] Linking CXX static library ../../../lib/libgtest_main.a
[ 21%] Built target gtest_main
[ 26%] Building CXX object CMakeFiles/MathTests.dir/cmake_pch.hxx.pch
In file included from <built-in>:1:
In file included from /home/kv/work/comp/loopmodels/Math/buildclang/nosan/CMakeFiles/MathTests.dir/cmake_pch.hxx:10:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:6151:14: error: requires clause differs in template redeclaration
    requires forward_range<_Vp>
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:5850:14: note: previous template declaration is here
    requires input_range<_Vp>
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:8846:20: error: type-id cannot have a name
    { return (auto(__x) += __y); }
                   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:8846:25: error: expected ')'
    { return (auto(__x) += __y); }
                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:8846:14: note: to match this '('
    { return (auto(__x) += __y); }
             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:8846:32: error: expected expression
    { return (auto(__x) += __y); }
                               ^
4 errors generated.
make[2]: *** [CMakeFiles/MathTests.dir/build.make:77: CMakeFiles/MathTests.dir/cmake_pch.hxx.pch] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/MathTests.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by chriselrod** [comment]
I think this project requires at least Clang 17 and GCC 13.
C++23 support is too limited in the older compiler versions, e.g. 
```
/home/kv/comp/loopmodels/Math/include/Math/Matrix.hpp:16:6: error: invalid types ‘long int[ptrdiff_t {aka long int}]’ for array subscript
   16 |   { t[i, i] } -> std::convertible_to<S>;
```
multidimensional array subscripts are new in C++23.

That said, lets focus on just clang-17, then.

That immediate problem should be fixed by https://github.com/LoopModels/Math/commit/cef07cc07c72cfb172e3cb4cf55d2be5112f3ae6 which makes `mmzero` properly `consteval` on clang.

Mind trying again?

**Comment by chriselrod** [comment]
> It worked with Clang 17!
> 
> The previous GCC error I posted is for GCC 13.
> 
> ```
> gcc (Ubuntu 13.1.0-8ubuntu1~20.04.2) 13.1.0
> ```

Ah, sorry, missed that. I might be on a patched version of gcc 13.2, since here (an issue I filed about this bug a few months ago) it says it was fixed with gcc 13.3:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111493

so while it works on my gcc 13.2.1, it's more precise to say gcc >= 13.3 and clang 17 that are supported.
